apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fint-monitoring-service
spec:
  itemPath: "vaults/aks-infra-vault/items/fint-monitoring-service"
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    io.kompose.service: fint-monitoring-service
  name: fint-monitoring-service
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: fint-monitoring-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-monitoring-service
  name: fint-monitoring-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-monitoring-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-monitoring-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/fint-monitoring-service:dummy
          name: fint-monitoring-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: fint-monitoring-service
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc'