apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-monitoring-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/fintlabs/fint-monitoring-service:sha-0000000
          name: fint-monitoring-service
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: fint-monitoring-service
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: '-XX:+ExitOnOutOfMemoryError -Xmx480M -verbose:gc'